import type { Metadata } from 'next';
import Menu from '@/components/Menu/Menu';
import { DM_Sans } from 'next/font/google';
import './globals.css';

const font = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Shop App',
   description: 'Generated by NT'
};

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={font.className}>
            <header>
               <Menu />
            </header>

            <div>{children}</div>
         </body>
      </html>
   );
}
